### Home

GET http://127.0.0.1:5000/


###

### Get All Tasks

GET http://127.0.0.1:5000/tasks


###

### Create Task

POST http://127.0.0.1:5000/tasks
Content-Type: application/json


{
    "title":"Learn MVC",
    "description":"Build scalable Flask API",
    "status":"pending"
}


###

### Invalid Task

POST http://127.0.0.1:5000/tasks
Content-Type: application/json


{
    "title":"",
    "description":"Testing",
    "status":"pending"
}


###

### Invalid Status

POST http://127.0.0.1:5000/tasks
Content-Type: application/json


{
    "title":"Deploy API",
    "description":"Production",
    "status":"wrong"
}