### Home
GET http://127.0.0.1:5000/

###

### Register
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username": "Sai",
    "email": "sai@gmail.com",
    "password": "hello123"
}

###

### Login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "email": "sai@gmail.com",
    "password": "hello123"
}